export const featuredBusiness = [
  {
    id: 1,
    name: "The Gourmet Kitchen And Restaurant and Spa and resort and swimming pool with fine dining",
    imgUrl: "https://via.placeholder.com/380x252?text=The+Gourmet+Kitchen",
    location: "123 Maple Street, New York",
  },
  {
    id: 2,
    name: "Sunrise Spa",
    imgUrl: "https://via.placeholder.com/380x252?text=Sunrise+Spa",
    location: "456 Oak Avenue, Los Angeles",
  },
  {
    id: 3,
    name: "City Bistro",
    imgUrl: "https://via.placeholder.com/380x252?text=City+Bistro",
    location: "789 Pine Road, Chicago",
  },
  {
    id: 4,
    name: "Health Haven",
    imgUrl: "https://via.placeholder.com/380x252?text=Health+Haven",
    location: "321 Elm Street, Houston",
  },
  {
    id: 5,
    name: "Luxury Lounge",
    imgUrl: "https://via.placeholder.com/380x252?text=Luxury+Lounge",
    location: "654 Cedar Avenue, Phoenix",
  },
  {
    id: 6,
    name: "Bistro Bliss",
    imgUrl: "https://via.placeholder.com/380x252?text=Bistro+Bliss",
    location: "987 Birch Road, Philadelphia",
  },
  {
    id: 7,
    name: "Relax Retreat",
    imgUrl: "https://via.placeholder.com/380x252?text=Relax+Retreat",
    location: "159 Maple Avenue, San Antonio",
  },
  {
    id: 8,
    name: "Gourmet Gallery",
    imgUrl: "https://via.placeholder.com/380x252?text=Gourmet+Gallery",
    location: "753 Oak Road, San Diego",
  },
  {
    id: 9,
    name: "Wellness Works",
    imgUrl: "https://via.placeholder.com/380x252?text=Wellness+Works",
    location: "951 Pine Street, Dallas",
  },
  {
    id: 10,
    name: "Cafe Comfort",
    imgUrl: "https://via.placeholder.com/380x252?text=Cafe+Comfort",
    location: "357 Cedar Road, San Jose",
  },
  {
    id: 11,
    name: "Serene Spa",
    imgUrl: "https://via.placeholder.com/380x252?text=Serene+Spa",
    location: "123 Birch Street, Austin",
  },
  {
    id: 12,
    name: "Dine Divine",
    imgUrl: "https://via.placeholder.com/380x252?text=Dine+Divine",
    location: "456 Maple Road, Jacksonville",
  },
  {
    id: 13,
    name: "Holistic Health",
    imgUrl: "https://via.placeholder.com/380x252?text=Holistic+Health",
    location: "789 Oak Avenue, Fort Worth",
  },
  {
    id: 14,
    name: "Elegant Eatery",
    imgUrl: "https://via.placeholder.com/380x252?text=Elegant+Eatery",
    location: "321 Pine Road, Columbus",
  },
  {
    id: 15,
    name: "Spa Serenity",
    imgUrl: "https://via.placeholder.com/380x252?text=Spa+Serenity",
    location: "654 Elm Street, Charlotte",
  },
  {
    id: 16,
    name: "Fine Dining",
    imgUrl: "https://via.placeholder.com/380x252?text=Fine+Dining",
    location: "987 Cedar Avenue, San Francisco",
  },
  {
    id: 17,
    name: "Tranquil Touch",
    imgUrl: "https://via.placeholder.com/380x252?text=Tranquil+Touch",
    location: "159 Birch Road, Indianapolis",
  },
  {
    id: 18,
    name: "Gourmet Delight",
    imgUrl: "https://via.placeholder.com/380x252?text=Gourmet+Delight",
    location: "753 Maple Street, Seattle",
  },
  {
    id: 19,
    name: "Blissful Bites",
    imgUrl: "https://via.placeholder.com/380x252?text=Blissful+Bites",
    location: "951 Oak Road, Denver",
  },
  {
    id: 20,
    name: "Relaxation Station",
    imgUrl: "https://via.placeholder.com/380x252?text=Relaxation+Station",
    location: "357 Pine Street, Washington",
  },
];
